name: Megatron-LM
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python
  - pip
  - boto3
  - google-cloud-language
  - inflect
  - nltk
  - numpy
  - pandas
  - regex
  - requests
  - tqdm
  - tensorflow-gpu<2.0,>=1.13
  - pytorch>=1.1
  - torchvision
  - cudatoolkit=10.0
  - nvcc_linux-64=10.0
  - pip:
    - sentencepiece
