name: Megatron_LM-ipy
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python>=3.6
  - pip
  - ipython
  - ipywidgets
  - nb_conda
  - boto3
  - google-cloud-language
  - inflect
  - nltk
  - numpy
  - pandas
  - regex
  - requests
  - tqdm
  - tensorflow-gpu<2.0,>=1.14
  - pytorch<1.3,>=1.2
  - torchvision
  - cudatoolkit=10.0
  - nvidia::nvcc_linux-64=10.0
  - openexr
  - future
  - pip:
    - sentencepiece
